export const projects = [
  {
    title: "Conte Interior - Furniture & Design Showcase",
    image: "/images/projects/conte.png",
    description:
      "A high-end interior design and commercial website for Conte Interior. Focused on delivering a premium visual experience with optimized performance, SEO-friendly architecture, and a custom-built CMS.",
    tech: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
      "Node.js",
      "Nginx",
      "VPS Hosting",
    ],
    demo: "https://conte.vn/",
    features: [
      "Premium UI/UX Design",
      "High Performance & SEO Optimized",
      "Custom CMS for Project Showcase",
      "Responsive Layout",
      "Smooth Interaction Animations",
    ],
  },
  {
    title: "ERP HTX9 - Transport Management System",
    image: "/images/projects/htx.png",
    description:
      "A comprehensive management platform for HTX Van tai 9. Developed modules for personnel management, financial cash flow tracking, and vehicle loan timelines to digitize traditional manual logistics workflows.",
    tech: ["React.js", "TypeScript", "Ant Design", "Python"],
    features: [
      "Personnel Management",
      "Financial Cash Flow Tracking",
      "Vehicle Loan Scheduling",
      "Dark/Light Mode",
      "Role-based Access Control",
    ],
  },
  {
    title: "Personal Portfolio",
    image: "/images/hero/hero.png",
    description:
      "A modern, responsive portfolio website with dark/light mode, multi-language support (Vietnamese/English), smooth animations, and interactive experience timeline. Built with Next.js 15, TypeScript, and Tailwind CSS.",
    tech: [
      "Next.js 15",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
      "React Hook Form",
      "i18next",
      "Vercel",
    ],
    demo: "https://my-porfolio-bui-cong-thachs-projects.vercel.app/",
    github: "https://github.com/buithachIT/MyPorfolio",
    features: [
      "Dark/Light Mode",
      "Multi-language",
      "Responsive Design",
      "Smooth Animations",
      "Experience Timeline",
    ],
  },
  {
    title: "Aurore - Modern Headless E-commerce",
    image: "/images/projects/aurore-thumb.png",
    description:
      "A high-performance Headless E-commerce platform built with Next.js 15 and React 19. It features a GraphQL-first architecture integrated with a Dockerized WooCommerce backend, providing a seamless and scalable shopping experience.",
    tech: [
      "Next.js 15",
      "React 19",
      "TypeScript",
      "Apollo GraphQL",
      "TailwindCSS",
      "Vitest",
      "MSW",
      "Docker",
    ],
    demo: "https://aurore-theta.vercel.app/",
    github: "https://github.com/buithachIT/NextJS_E-commerce",
    features: [
      "Headless WooCommerce Integration",
      "GraphQL API & Type-safe Codegen",
      "Unit Testing with Vitest & MSW",
      "Responsive UI & Fluid UX",
      "Dockerized Backend Infrastructure",
    ],
  },
  {
    title: "Spotify Clone",
    image: "/images/projects/spotify.png",
    description:
      "A full-featured music streaming platform with manage playlist, user, payment, and admin dashboard.",
    tech: [
      "React",
      "Python",
      "MySQL",
      "Flask",
      "HTML",
      "CSS",
      "TypeScript",
      "Tailwind",
      "Antd Design",
      "React Router",
      "React Query",
    ],
    github: "https://github.com/buithachIT/ListenToMusicWeb",
    features: [
      "Music Streaming",
      "Playlist Management",
      "User Authentication",
      "Payment Integration",
      "Admin Dashboard",
    ],
  },
];
